### ISSUE TITLE
WindowsSettings results cluttering other results

### ISSUE THREAD

**Issue by skjerns** [Flow-Launcher/Flow.Launcher#1008]
Currently, when enabling the `Windows settings` plugin, a lot of sub settings and pages are being displayed and clutter the search results. They come in two categories: `System settings` and `Control panel`

![image](https://user-images.githubusercontent.com/14980558/152189296-0eae9ef1-8fce-4b17-9075-5f4a37d45376.png)

It would be great if it could be disabled which of the two categories are being displayed. In my opinion, `Control Panel` setting pages are just too many and you never find the one you're looking for. `System Settings` are mostly useful.

**Comment by jjw24** [comment]
The root problem is the WindowsSettings had an intentional score bumping, which resulted in its returned results higher than all other plugins. This is removed in the referenced PR, can you give it a go with this [portable version]( https://ci.appveyor.com/api/buildjobs/aa4uamuq3k3wtp1o/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip) from the pr and let me know if this is a better fix.

**Comment by jjw24** [comment]
Closing. Please try the pre-release or wait for v1.10.0, and if still an issue feel free to reopen.
