### ISSUE TITLE
Add a shortcut system like the UELI launcher 

### ISSUE THREAD

**Issue by s0902rx** [Flow-Launcher/Flow.Launcher#1027]
**Is your feature request related to a problem? Please describe.**

I'm a noob that would like to create shortcuts to file paths and urls etc but i don't even know how to create a .conf file for the "favorites" plugin.

**Describe the solution you'd like**

Implement something like the UELI launcher that has a graphic interface where you can set shortcuts and access them with the launcher by typing the name or the tag that you assigned to the shortcut which is way easier for people like me.

What it looks like:

https://user-images.githubusercontent.com/79232286/154003771-898b86bf-42b3-491f-b421-70653c057069.png

**Describe alternatives you've considered**

Using both the Ueli and flow launcher.

**Comment by jjw24** [comment]
For file path, you can use quick access- go to context menu of your chosen file or folder, then select add to quick access. You can then go to plugin settings to add an action keyword to quick access which will then allow you to bring up your saved file paths.

For saving urls, would you not want to saved it to your bookmarks then access it via the bookmark plugin?

We currently don't have such implementation to allow universal access to all your saved file paths due to the fact that each plugin is independent from the other. For Favourites plugin which sounds like can help with this, you should create an issue to let the developer know about creating an UI to help setting up these shortcuts, I think it would be feasible as not everyone would want to deal with creating config files manually. Let me know if you are not sure where to go to create a suggestion for the Favourites plugin.

**Comment by s0902rx** [comment]
I thought about doing what you suggested for the file paths but then i realised that doing windows+e and clicking on your quick access paths was much simpler.

Being able to just open your launcher type your keyword and have windows explorer open the file path without having to read (if you touch type) is much much more useful and easy to set up. 

And for the browser bookmarks i don't think there is a bookmarks folder for Brave-browser or i just might be too dumb.

**Comment by taooceros** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/pull/930
what about this? Expand a specific query to a longer string

**Comment by deefrawley** [comment]
As I use Everything and File Explorer together I've given the File Explorer plugin a keyword (`ex` in my case). If you add dirs to the Quick Access settings for that plugin, then when you type the keyword you instantly get a list of them which means you can select from the list.
You could also use the Program Runner to setup Explorer (or your favourte file manager) shortcuts to your favourite directories and then give that a shortcut. Could do the same for browser and URL's

**Comment by jjw24** [comment]
Alternatives have been provided
