### ISSUE TITLE
Some of my folders don't appear in Flow Launcher

### ISSUE THREAD

**Issue by PaulBerta** [Flow-Launcher/Flow.Launcher#1082]
![image](https://user-images.githubusercontent.com/63358302/158250021-7fd4f6de-beb1-4cb7-b437-032ca5a850b2.png)

![image](https://user-images.githubusercontent.com/63358302/158250043-40a5f81c-86f4-46e1-92d1-ed90222976b9.png)

This behavior is the same for every folder that is outside C:\ProgramData if I search by name.

I can see the other folders if I search by directory:

![image](https://user-images.githubusercontent.com/63358302/158250489-d578e754-a402-4e52-8b9e-4410a67b3a1a.png)

Any idea why this is happening?

**Comment by jjw24** [comment]
Hi @PaulBerta this is likely due to your Windows Index configuration. If you go to Indexing Options, you should see what directories are indexed by Windows. You can further adjust what should and should not be following this screenshot:

![image](https://user-images.githubusercontent.com/26427004/158256336-c81eb6ec-79f3-4e22-b571-f3892cd9cd69.png)

Once you have configured your indexed directories, please remember to rebuild the index:

![image](https://user-images.githubusercontent.com/26427004/157117746-e0f5982c-2ad9-41cd-8148-c32c0663f708.png)

Please reopen if you still have issues.
