### ISSUE TITLE
How do we add the Everything plugin back?

### ISSUE THREAD

**Issue by giggio** [Flow-Launcher/Flow.Launcher#135]
**Question**
I saw that the everything plugin is not there anymore. How do we add it back? It is not published on http://www.wox.one/plugin and it does not have a release on https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything.

**Comment by jjw24** [comment]
Are there still functionalities you need from Everything that's not covered in Explorer plugin?

**Comment by giggio** [comment]
Windows Search does not index my whole drive, and I don't want it too, as it is too slow and takes up a lot of cpu. Everything scans all of it, super fast.

**Comment by jjw24** [comment]
When you say slow, is it the indexing part that's slow? Because searching is very fast with Explorer.

I am away from comp at the moment, when I get back I will publish a download in the Everything repo users can use should they want to keep Everything plugin.

In the meantime if you still want to use the new version, you can grab the Everything plugin from previous version and copy it across to the new version, dump it in the user data location's plugin folder (same location where custom plugins are stored).

Apologies for the inconveniences.

**Comment by giggio** [comment]
Yes, indexing is slow, searching is fast.
I'll wait for the release, thanks!

**Comment by jjw24** [comment]
Hey it's now available in the repo's release page https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/releases/latest

**Comment by fdawans** [comment]
Is there a way to make it work with a portable installation of Everything ? 
It was working with Wox for me. 

See #143

**Comment by jjw24** [comment]
> Is there a way to make it work with a portable installation of Everything ? 
> It was working with Wox for me. 
> 
> See #143 

Where can I download the portable version of Everything, or is it a setting within Everything I need to select?

**Comment by fdawans** [comment]
I used the portable zip 64bit [https://www.voidtools.com/downloads/](url)

**Comment by jjw24** [comment]
> I used the portable zip 64bit: [https://www.voidtools.com/downloads/](url)

Ok cool, I will play around with it and let you know

**Comment by fdawans** [comment]
FYI, I managed to install Everything as an admin so it works for me now.
It would still be nice if it would work without.

**Comment by cyber2e** [comment]
Really bad that everything is not in the default installation file. It is the top 1 feature I expect from this launcher.
