### ISSUE TITLE
[Question] Why is the app size much larger than wox ?

### ISSUE THREAD

**Issue by AmrBinBashir** [Flow-Launcher/Flow.Launcher#138]
Why is the app size is 80mb compared to original wox which is around 5mb ?

**Comment by jjw24** [comment]
The main reason it's at 80mb is because Flow is built with .Net Core 3.1 and published as a self-contained Core application. This means users do not need to install .Net Core run time (like you would with .Net Framework), as all required run time files are embedded with the application files. This also means users can use portable mode and use it on all Win 7 + machines without needing to install anything additional.

**Comment by AmrBinBashir** [comment]
That's pretty cool actually but I think you should provide a lightweight version without dependencies and let the user install .net core by himself. I mean there is a lot of ppl out there that might have .net core already installed like me so the lighter version would be prefect in this situation.
Awesome app though.
