### ISSUE TITLE
BUG: Themes Dissapeared upon last update of flow launcher

### ISSUE THREAD

**Issue by kaylamillerdev** [Flow-Launcher/Flow.Launcher#1437]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I updated to version 1.9.5 and now all themes are completely gone, including my custom theme. 

### To Reproduce

1. update to latest version (1.9.5)
2. check in themes folder and see no themes files
3. ...

### Screenshots

![ka24vUJahl](https://user-images.githubusercontent.com/52870645/193431456-8df7352b-8393-4e7d-94a1-45e130988c5e.png)

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.19044.2006

### Error Log

[2022-10-01.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9691347/2022-10-01.txt)

**Comment by deefrawley** [comment]
Hi, pretty sure that is normal as that folder is for custom themes. If you go to Settings - Themes you should be able to still choose a system theme.

**Comment by kaylamillerdev** [comment]
@deefrawley The problem is that I need to see the theme files in order to clone one to rewrite my custom theme. Additionally, before this update, there WERE theme files in there.

**Comment by deefrawley** [comment]
@onesounds can you advise?

**Comment by onesounds** [comment]
@kaylamillerdev I'm sorry. I need to ask you a few questions. 
- Is it possible you use default themes? or Is it impossible to execute flow in this situation?
- No item in theme list?
- Check two directories.
- C:\Users\...\AppData\Local\FlowLauncher\Themes
- C:\Users\...\AppData\Roaming\FlowLauncher\Themes

**Comment by Garulf** [comment]
The `Roaming` folder is Userdata while `Local` is the Application directory. 

All bundled Icons and Themes are typically in the Application directory not userdata.

**Comment by jjw24** [comment]
By design, everything in C:\Users...\AppData\Roaming\FlowLauncher\ should not have been touched, only files in the app directory C:\Users...\AppData\Local\FlowLauncher\ will.

If by accident your themes for whatever reason is placed in the app directory's themes folder, the update should also have made a back up of the app directory, if you go to C:\Users...\AppData\Local\FlowLauncher, you should see a couple versioned folder and one with v1.9.4. Check the themes folder there to see if it has your custom themes.

**Comment by kaylamillerdev** [comment]
@jjw24 That was it. My themes were in the appdata>Local>FlowLauncher>app-1.9.4>themes. 

Maybe a consideration would be to have the theme button in the launcher go to the appdata local folder instead of app data romaing folder. 

Does this mean that every time i update I have to copy and paste my theme from the previous version to the current version? That's gonna get annoying.

**Comment by onesounds** [comment]
> Does this mean that every time i update I have to copy and paste my theme from the previous version to the current version? That's gonna get annoying.

No. Just put themes in the Roaming path. You don't need copy and paste every time.  Local is not recommended to place the file because there may be changes during the update. (Because 'open theme folder' target is Roaming) The custom theme file to be placed in Roaming. Flow is supposed to read this place and add it to the theme.  It works even if you put it there.(roaming)

We designed to use the theme in Roaming folder because of our intentions, and we made the button like that. There may be confusion like you, so I'll add a brief explanation to the theme document.

**Comment by jjw24** [comment]
Doc has been updated https://www.flowlauncher.com/docs/#/how-to-create-a-theme, which is what @onesounds has mentioned.

@kaylamillerdev are you able to recover your themes from the backup located inside your appdata>Local>FlowLauncher>app-1.9.4? The current version would be appdata>Local>FlowLauncher>app-1.9.5

**Comment by jjw24** [comment]
Glad to hear. If you would like, please consider sharing your theme as well here 
https://github.com/Flow-Launcher/Flow.Launcher/discussions/1438
