### ISSUE TITLE
BUG: FL 1.10.0 (10.10.2022) Incorrect icon

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#1462]
In the action sheet with files, the "Delete File" icon is not correct.
The folder icon should change to a file icon.

![221010 FL 1 10 0_10 10 22 Icono de archivo_Incorrecto](https://user-images.githubusercontent.com/102802425/194947762-0a5827fc-c193-4933-82cd-3c119d917b24.png)

**Comment by dracp** [comment]
> Thanks @dracp, do you have a link to the proposed icon image?

I have directly made a composition by copying and pasting the icons from the graphic interface of the program.
If you send me the original icons of the folder with the circle and the file, I have no problem to generate the proposed icon.

**Comment by jjw24** [comment]
@onesounds thoughts?

**Comment by onesounds** [comment]
I'll change the icon to recycle bin.

**Comment by dracp** [comment]
I insist
If you send me the original icons of the folder with the circle and the file, I have no problem to generate the proposed icon.

![221011 FL 1 10 0 10 08 22_Iconos_carpeta_archivo](https://user-images.githubusercontent.com/102802425/195029724-70cb4b08-897e-4491-b079-da02ceac5a02.png)

**Comment by onesounds** [comment]
Icon making is not problem. I'm not bothered by this work. The original can be found in this repo. 

<img src="https://user-images.githubusercontent.com/6903107/195036587-3c6dcb10-de8e-4a0e-a856-be2afc134d65.png">

1. Although those two items appear to be separated, icon items are used in common on the code. I don't know who made this code, but it's not a bug and it's an intended implementation.
2. I can modify the code. but The problem is that this item is currently a code under full revision in #1097, so even if it is modified here, it needs to be corrected from the beginning again.

3. I think the design of this item should be changed to a trash can without distinguishing it. (Same is the copy item. it don't need to two icon.) This is because it is usually designed that way in the context menu. Other apps do not display deletion functions separately according to folders or files.  I think existing method is wrong because the delete mark is not emphasized.

![image](https://user-images.githubusercontent.com/6903107/195038366-18d4a0c5-691e-44f1-b412-8dc6366d3dd8.png)

![image](https://user-images.githubusercontent.com/6903107/195038148-9cc1d0cb-7332-4d89-9605-c84bfadff1d4.png)

I think your problem is right, but I disagree with the direction of correction. 
Anyway, I don't want to give you the impression of being hard on. I think it doesn't matter if it changes because I didn't pay attention to this item. I'll do what you want.

**Comment by dracp** [comment]
I have no particular interest. It is your program. Do what you consider.
Greetings

**Comment by jjw24** [comment]
Hey, I may have had a hand in misusing the icon due to an oversight or just lazy (likely lazy 😛 ) , so thank you @dracp for picking up this bug, great attention to detail. I think what @onesounds is suggesting is have one icon that works for both scenarios (delete file and delete folder), same way Microsoft is doing for its delete icon. This will also make the code a little bit easier so we don't need to differentiate what icon to show based whether it's a file or folder that is being deleted, so let's just use a single icon instead.

**Comment by dracp** [comment]
> Hey, I may have had a hand in misusing the icon due to an oversight or just lazy (likely lazy 😛 ) , so thank you @dracp for picking up this bug, great attention to detail. I think what @onesounds is suggesting is have one icon that works for both scenarios (delete file and delete folder), same way Microsoft is doing for its delete icon. This will also make the code a little bit easier so we don't need to differentiate what icon to show based whether it's a file or folder that is being deleted, so let's just use a single icon instead.

Perfect. What you consider best.
