### ISSUE TITLE
[Dev] BUG: Plugins in Settings plugin list should auto adjust its height when expanded 

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1507]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

@onesounds when a plugin is expanded in settings, it should automatically adjust to the top of the window so the plugin settings are fully visible, this behavior is present in the production release, did we remove this in Dev?

### To Reproduce

1. Go to flow's settings
2. Click program plugin's settings, observe it is expanded but half of the settings is cut off because it no longer automatically snap to the top of the window.
3. Do the same with 1.9.5 release and see that the plugin snaps to the top and at least most of its settings is visible.

### Flow Launcher Version

Dev

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by onesounds** [comment]
1. I've never touched this part. In addition to this problem, there are other bugs that are not in production, so it seems that there was a mistake when merging. (as you know, it's not easy to tracking. because everything in setting window. TT)
2. It's an interesting situation. This scroll problem is exactly what the dev version intended. The production state is the version I left because I couldn't fix it and it's good too. (problem : recently, I didn't touch this part as I remember! 😂) 
3. This is more correct to be in dev because the location of the item changes regardless of the user's intention. (Same as PowerToy setting window or Windows 11 setting.)

I think it's a problem that doesn't need to be fixed in now. The dev version is a more accurate move.
----
p.s oh, I remember @taooceros  removed custom control panel's max height. This change may cause this.

**Comment by jjw24** [comment]
Sorry, I think it was @taooceros that added this in.

>I think it's a problem that doesn't need to be fixed in now. The dev version is a more accurate move.

Hm ok.

**Comment by onesounds** [comment]
> Sorry, I think it was @taooceros that added this in.

It's OK. It's not his fault, He asked me about it as I remember.
