### ISSUE TITLE
BUG: Right click on search result not working

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#1542]
I tried to multiple OS systems and right click on search items not working.
When I right-click, the context menu does not appear.

I use dev build (Portable).

**Comment by onesounds** [comment]
It happen in dev. (and tooltip doesn't work too.)
This problem appears to be caused by drag and drop PR.
There are Mainwindow's Click things (old) and ResultListBox's click thing (new) both exist. but only new one works.

**Mainwindow.xaml**
![image](https://user-images.githubusercontent.com/6903107/202716827-8780773a-48bd-483b-b59f-a0a1f35f1055.png)
**ResultListBox.xaml**
![image](https://user-images.githubusercontent.com/6903107/202716946-1c413293-1c18-4507-bf4a-5d365187ab35.png)

I tried to fix but it's not my capacity. help here. @taooceros

**Comment by taooceros** [comment]
I think the current result handling is a bit dirty due to logic handling is in the mainviewmodel. I will check soon.

**Comment by kubalav** [comment]
@VictoriousRaptor Is it working for you? Right click menu is showing correctly now, but exception occure after I click to e.g. Set as topmost in this query.

**Comment by VictoriousRaptor** [comment]
> @VictoriousRaptor Is it working for you? Right click menu is showing correctly now, but exception occure after I click to e.g. Set as topmost in this query.

It's by @taooceros in #1558. Yeah I can reproduce.

**Comment by kubalav** [comment]
It's fixed.
