### ISSUE TITLE
Fully claerup query And Result blacklist

### ISSUE THREAD

**Issue by KJH-x** [Flow-Launcher/Flow.Launcher#1662]
感谢大佬们开发这个软件！
Hi, thanks for the excellent work.
> 以下部分英文说明由谷歌翻译而来，可能有歧义。
> Some part of the following description in English is translated by Google, which might be ambiguous.

**Is your feature request related to a problem? Please describe.**

- 我不确定这是否是一个可以解决的问题，但我希望能在下次唤醒时，搜索框退出二级菜单并清空搜索内容。
- I am not sure about this, but I want to clear the query and quit the secondary menu on the next use. 
- 现在的情况是我在进入二级菜单后，选择选项，在下次唤醒时仍然保留了搜索内容。
- The current situation is that after I enter the secondary menu, select an option, and it will still keep the content of the search when I wake it up next time.
<br>

- 第二个问题，我希望能把一些结果禁止显示，比如<Restart With Advanced Boot Options>，它的二级菜单中没有如<程序>插件提供的<禁止显示该程序>的类似选项。
- The second is, I hope to disable some results, such as <Restart With Advanced Boot Options>, its secondary menu does not have a similar option as <Disable this program from displaying> provided by the <Program> plug-in.

**Describe the solution you'd like**

- 我认为可以在设置中增加一个选项，以达到选择了二级菜单选项后，下次唤醒时，是空白搜索栏的目的。
- I think an option can be added in the settings to achieve the purpose of blanking the query bar the next time after selecting an secondary menu option.
- 禁止搜索项可以被作为一个全局项，而不是每个插件各自做。比如在everything插件中会也会搜索到一些不需要的文件，此时的搜索黑名单将比较有用。
- Suppressed specific result(s) can be made as a global option instead of achieveing it individually in each plugin. For example, some unwanted results will be shown by the everything plug-in. At this time, a search blacklist will be useful.

**Describe alternatives you've considered**

暂无，not yet.

**Additional context**
![截图_20221216175243](https://user-images.githubusercontent.com/53437291/208072137-7773b907-898d-48e7-a589-6716133d0c9d.png)

**Comment by taooceros** [comment]
有一个draft了，还没完全确定是否应该这么做

**Comment by jjw24** [comment]
>我不确定这是否是一个可以解决的问题，但我希望能在下次唤醒时，搜索框退出二级菜单并清空搜索内容。
I am not sure about this, but I want to clear the query and quit the secondary menu on the next use.
现在的情况是我在进入二级菜单后，选择选项，在下次唤醒时仍然保留了搜索内容。
The current situation is that after I enter the secondary menu, select an option, and it will still keep the content of the search when I wake it up next time.

This has been fixed and will be going out in the next release.

**Comment by jjw24** [comment]
>第二个问题，我希望能把一些结果禁止显示，比如，它的二级菜单中没有如<程序>插件提供的<禁止显示该程序>的类似选项。
The second is, I hope to disable some results, such as , its secondary menu does not have a similar option as provided by the plug-in.

User proposed solution:
>禁止搜索项可以被作为一个全局项，而不是每个插件各自做。比如在everything插件中会也会搜索到一些不需要的文件，此时的搜索黑名单将比较有用。
Suppressed specific result(s) can be made as a global option instead of achieveing it individually in each plugin. For example, some unwanted results will be shown by the everything plug-in. At this time, a search blacklist will be useful.

This is going to be hard to implement as global as we need to dynamically populate all results for users to select. It's better to improve flow's actual search mechanism so searching is more accurate.

Closing for now, happy to reopen for further discussion if needed.
