### ISSUE TITLE
Delay restart after plugin install/uninstall

### ISSUE THREAD

**Issue by KAGEYAM4** [Flow-Launcher/Flow.Launcher#1685]
**Is your feature request related to a problem? Please describe.**

Currently if we install/unistall a plugin , flow launcher needs to be restarted (which it does automatically), and we have to wait for it to restart so that we can intall/unistall another plugin.

**Describe the solution you'd like**

A pending Operation popup, which notifies that there are pending changes for plugins and flowLauncher needs to be restarted. 
So that user can choose when to restart after performing all of its installation/uninstallation of plugins.

**Describe alternatives you've considered**
A way to postpone the automatic restart.

**Comment by PhoenixCODE2322** [comment]
i tried `pm install/uninstall` command and it makes it more usable but still , a support to restart on user's choice would be great.

**Comment by TG-DylanH** [comment]
Completely agree on this. I just installed Flow Launcher, and as I'm looking through the Plugin Store, there's a ton of plugins that look fantastic that I want to install.

However, the fact that I have to restart the program for each install is beyond infuriating, and I'll likely end up not installing a lot of plugins just due to the time requirement for this.

**Comment by jjw24** [comment]
Well fortunately this feature has already been built in 1.17.0, look for it in the PluginsManager settings. We just forgot to close this 😃
