### ISSUE TITLE
[Program plugin] Show shorcut icon for shortcuts

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#1806]
**Is your feature request related to a problem? Please describe.**
Right now if you search for a program, the shortcut and the main program show the same icon.

**Describe the solution you'd like**
The shortcut arrow should appear on icons that are shortcuts

**Describe alternatives you've considered**
Opening the containing folders of both the programs one by one to find out which one contains the actual exe

**Additional context**

I needed to copy the path for the main mpv exe and this was the search result:
<img width="435" alt="Screenshot_20230116_033619" src="https://user-images.githubusercontent.com/47380919/212676987-9e72a37a-27ae-48fc-853b-7a2deb64c4d2.png">

One of the icons was the main exe and the other one was a shortcut.

**Comment by z1nc0r3** [comment]
I think it is supposed to show the application name with the ".lnk" suffix. Like below ss

![image](https://user-images.githubusercontent.com/64279853/212971113-7b1b5f62-4eaf-48e3-a58c-42327f351641.png)

In case it is not working, please try toggling this in the **Program plugin**

![image](https://user-images.githubusercontent.com/64279853/212971488-39b057fc-fe5c-49c7-87ac-4295e71bb510.png)

**Comment by z1nc0r3** [comment]
Does this issue happens for every program or only for certain applications?

**Comment by onesounds** [comment]
> This would be a good idea to distinguish between which app is a shortcut or not. I'll look into if this is possible.

If you create this function, on/off should exist. (off must be the default setting.)

**Comment by onesounds** [comment]
I leave my objection to this proposal.

OS marks shortcut arrow as a layer to distinguish it from exe. However, even on the OS, this arrow does not appear on the Start menu or the taskbar. Because it's kind of a Launcher area. I think that this distinction is unnecessary because the program plugin is also a plug-in for 'execution'.

I think it's meaningful that arrows exist because I think desktop or explorer plug-ins are areas of search and management. I think this problem should be handled by the Explorer plug-in. This problem occurs in situations where you try to 'manage' with a plug-in for 'execution'.

Anyway, it doesn't matter if it's in the program plug-in. it shouldn't be the default. This arrow is aesthetically problematic and therefore removed and displayed in some areas. 

For your information, I added the 'Hide app path' option of the program plugin for the same reason. (The function "execution" was basic and aesthetically unnecessary, so it was based on hiding.)
