### ISSUE TITLE
BUG: plugin settings won't save, always reset to default settings

### ISSUE THREAD

**Issue by raytedjaja** [Flow-Launcher/Flow.Launcher#1877]
### Checks

- [ ] I have checked that this issue has not already been reported.

### Problem Description

plugin:

1. wallpaper engine profile selector
2. currencyPP

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.12.1

### Windows Build Number

10.0.19045.2486

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by z1nc0r3** [comment]
Sorry, but I couldn't repro the issue.
FL has a command to save all FL settings manually. Please try the `Save Settings` commands if it keeps the plugin settings.

**Comment by jjw24** [comment]
Potentially related to https://github.com/Flow-Launcher/Flow.Launcher/issues/1853, please try this build here and let us know if addresses the problem https://ci.appveyor.com/api/buildjobs/fpolnta6i7na6npu/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

**Comment by raytedjaja** [comment]
> Sorry, but I couldn't repro the issue. FL has a command to save all FL settings manually. Please try the `Save Settings` commands if it keep

**Comment by kudlav** [comment]
The problem is that the Save settings button is missing in Flow Launcher plugin page.

I can recreate it with Flow Launcher 1.16.2 and CurrencyPP 3.0.1.

1. Change Output currency
2. type `10 USD`
3. All settings are reverted by CurrencyPP

The workaround is:
1. Disable CurrencyPP plugin
2. Change Output currency
3. type `Save Settings`
4. Enable CurrencyPP plugin

This is not intuitive at all.

![obrazek](https://github.com/Flow-Launcher/Flow.Launcher/assets/11516259/511dc025-b005-448d-a5d3-f35e4e37eb5f)

**Comment by z1nc0r3** [comment]
The issue seems related to plugins that are developed using Python. I checked a few Python plugins and found that we have to run the "_Save Settings_" FL command to save settings. I didn't refer to the documentation for Python plugins, so don't have a clear idea about how the saving process happens.

And, in the workaround mentioned by @kudlav, the "**Disable CurrencyPP plugin**" step is not necessary. You can just run the "_Save Settings_" command after changing the configs.

**Comment by kudlav** [comment]
If the plugin listens to every command `*`, then, the plugin will reset your unsaved setting when you will try to invoke `save settings`. That's why it's important to disable the plugin first.

**Comment by Garulf** [comment]
All plugins using my library Flox have this issue. 

Flox was created to allow plugins to support both Flow Launcher and legacy Wox. 

Wox does not have a mechanism for saving settings for a Python based plugins. In order to support this Flox had functionality to save to the settings file directly. 

Unfortunately due to a bug instead of intelligently using this functionality only for Wox it would save to file on Flow Launcher too! This wasn't a problem until Flow Launcher's settings saving mechanism was changed to only write to disk when exited. 

Flox is being retired, no one really uses Wox and support is cumbersome. I am hoping to move any plugin using Flox to a Flow Launcher only focused library called pyFlowLauncher, which has none of these issues. 

I apologize for any issues and hope to have this fixed in the coming weeks.
