### ISSUE TITLE
[FEATURE REQUEST] Multiple action keywords in one plugin

### ISSUE THREAD

**Issue by nikolicpetar17** [Flow-Launcher/Flow.Launcher#1965]
I don't know if this already exists but I would like to be able to add multiple action keywords to one plugin or at least to be able to show plugin results with and without typing keyword. 
Great program by the way, thanks for keeping it free.

**Comment by jjw24** [comment]
Hi there, thank you for the suggestion.

>I don't know if this already exists but I would like to be able to add multiple action keywords to one plugin

This doesn't exist, could you explain what scenario you would need this.

>be able to show plugin results with and without typing keyword

You can show results without keyword by using '*' this as a keyword, this the global wildcard for plugins to activate without action keyword.

**Comment by nikolicpetar17** [comment]
Thanks for replying, i know taht you can use * to show results without typing in keyword, but i would like to be able to have both option to not type keyword and option to type it in when i want to be more specific

**Comment by jjw24** [comment]
Ok i see.

**Comment by jjw24** [comment]
Ok I see. This can be achieved atm like the Explorer plugin. It is up to the plugin maintainers to build it in. Which plugin/s are you referring to?

**Comment by nikolicpetar17** [comment]
I tought it could be built directly into flow launcher, because it could be useful in pretty much any plugin and i think its not hard to implement

**Comment by nikolicpetar17** [comment]
For me most useful example would be spotify plugin where when you type its shortcut it shows you currently playing song and list of controls for it, but I also wan't to search songs without typing in the keyword. 

This is only one example and I think that it could be useful in almost all of plugins because you can get more suggestions and more results when keyword is typed in and faster search because you don't need to type in keyword every time 

I thought that this feature could be implemented by allowing multiple action keywords for one plugin, and then user can set one of them to "*" to be able to show results without typing keyword

**Comment by nikolicpetar17** [comment]
Microsofts PowerToys Run also has this feature to some extent, there you have an option to type in the action keyword but you can also toggle on "Include in global result" and it will show you results of that plugin without typing in keyword

![Screenshot 2023-05-21 232816](https://github.com/Flow-Launcher/Flow.Launcher/assets/127212737/3cf0d4f0-0cac-457c-9c71-efb837b865db)

**Comment by jjw24** [comment]
This already exists.

In a plugin's plugin.json file, instead of using the "ActionKeyword" field, use "ActionKeywords", and set the value as ["*", "a"]. Flow will query the plugin whenever `a` or any text is typed.

In the plugin code, just need to handle when query's action keyword is `*` or `a`. Follow Explorer plugin as an example.

**Comment by jjw24** [comment]
Closing this. Feel free to reopen if further discussion is required.

**Comment by seesmof** [comment]
I want to define multiple action keywords for different Web Searches plugin's actions, which is built in, but I dont think it supports ActionKeywords parameter. Whenever I tried replacing ActionKeyword with ActionKeywords, after app's restart it just reverted back to the defaults. 

My use case is that I use two keyboard layouts, but one is Cyrillic and the other one is Latin, so I cannot define a keyword which is one latin letter so that its compatible with both layouts. That makes me wonder, am i missing something, or is this features just not implemented? Thanks

**Comment by VictoriousRaptor** [comment]
> I want to define multiple action keywords for different Web Searches plugin's actions, which is built in, but I dont think it supports ActionKeywords parameter. Whenever I tried replacing ActionKeyword with ActionKeywords, after app's restart it just reverted back to the defaults.
> 
> My use case is that I use two keyboard layouts, but one is Cyrillic and the other one is Latin, so I cannot define a keyword which is one latin letter so that its compatible with both layouts. That makes me wonder, am i missing something, or is this features just not implemented? Thanks

Please make sure Flow is not running when you are editing the json file.
