### ISSUE TITLE
[FEATURE REQUEST] Option to limit number of results of specific plugin

### ISSUE THREAD

**Issue by nikolicpetar17** [Flow-Launcher/Flow.Launcher#1976]
I would like to limit number of results from some of the plugins, for example I use google search from Web searches plugin (I have it's keyword set to *) and I would like it to show me just 1 or 2 results but currently it shows much more. I also don't want to set its priority level lower becouse I want it to show om top.
![Screenshot_63](https://user-images.githubusercontent.com/127212737/224570752-de73bc0f-dff0-46a4-8acd-2ae59ab873e7.png)

**Comment by onesounds** [comment]
A short-term solution is to turn off "Use Search Query Autocomplete" (this is located in the lower right-hand corner of the web search plugin settings panel).

**Comment by nikolicpetar17** [comment]
> A short-term solution is to turn off "Use Search Query Autocomplete" (this is located in the lower right-hand corner of the web search plugin settings panel).

Thanks but it works just for web search, i whould also like to limit some other plugins like explorer and spotify

**Comment by jjw24** [comment]
This must be implemented by the plugins themselves, because if we set a global limit of results per plugin, flow has no way of knowing which results are relevant for the limit set. If plugins implement this, they can have a setting on their plugin to say return top 5, and the plugin code would work out which relevant ones it would return.
