### ISSUE TITLE
BUG: F1 preview of images does not fill the whole preview area

### ISSUE THREAD

**Issue by TheBestPessimist** [Flow-Launcher/Flow.Launcher#2030]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I have a bunch of JPEG and PNG images which i use as wallpapers, so they all have resolution of 1080p or higher.

While using FL to search and preview my pictures, it seems picture preview does not fill the whole preview area: some pics are small, others are larger, etc

What I expected is that FL fills the preview area according to the "highest dimension (of the pic/preview area)" or somehow the biggest ratio of pic vs preview area.

### Screenshots

Please see here: https://cdn.discordapp.com/attachments/917500039931256933/1093227949655855134/FL_preview_issue.gif

### Flow Launcher Version

1.14.0. some beta version

### Windows Build Number

Microsoft Windows [Version 10.0.22621.1485]

**Comment by ligq** [comment]
I also have this issue.

**Comment by taooceros** [comment]
you mean this? https://github.com/Flow-Launcher/Flow.Launcher/blob/8f58d53b8a3a9eedc13e2be1cf7fb5f9e0950ad9/Flow.Launcher.Infrastructure/Image/ImageLoader.cs#L288-L322

**Comment by TheBestPessimist** [comment]
bad bot

**Comment by VictoriousRaptor** [comment]
Looks like comment doesn't remove stale label.

**Comment by onesounds** [comment]
This issue will be resolved so that the image fills the preview panel area as much as possible.
However, you may find that the image resolution is low (it's set low because it affects the speed of the program), and I'll consider a separate setting for this. (but in now. this is low priority work. ) 
If you need to check high-resolution images, you're better off using quicklook, (we're working on support for quicklook, which will be merged soon.)
