### ISSUE TITLE
BUG: Everything Search Not Working

### ISSUE THREAD

**Issue by AaronB2019** [Flow-Launcher/Flow.Launcher#2128]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Uninstall everything plugin and changed the settings of explorer plugin to everything. But it doesn't seem like it is using everything and instead still using windows index. Because the Windows Index only indexed my D: Drive but not my C: Drive while Everything indexes everything. But, no searches is coming out at all. Below shows images shows the explorer plugin settings and also the file trying to be searched.

Also, content search means searching the content INSIDE of the file right? means if test.txt has a sentence inside that is "nice to meet you", it will show up if I search "doc: nice to meet you"?

### To Reproduce

1. Create file anywhere.
2. Search the file using doc:
3. Nothing comes out.
4. Search the file without using doc:

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/2adc3276-d07c-47e8-97bc-778114b7d4d6)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/0d82cff4-2aca-46a9-8e4d-9c9ac5a48c78)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/fc579e67-a613-4b59-ad1f-1d6f7cc5f68d)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/4b135b73-e6fc-4a03-baa9-54bca1a00741)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/fa2345c8-30b9-48fa-9352-d6aa7bcc013c)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/03378a3d-ffe5-4ef1-9723-2a32007d6c38)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/a91f8119-f342-45e6-9c41-378eb096a1c5)
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/100905825/8385131e-45a6-4df5-9919-0a802a51fc61)

### Flow Launcher Version

1.15.0

### Windows Build Number

22621.1702

**Comment by VictoriousRaptor** [comment]
Please refer to [this](https://www.flowlauncher.com/docs/#/plugin-explorer-usage?id=customised-action-keywords-tab) link to set up your Explorer plugin's keyword. `test.txt` matches no result because you're not using the keyword.

> Also, content search means searching the content INSIDE of the file right? means if test.txt has a sentence inside that is "nice to meet you", it will show up if I search "doc: nice to meet you"?

That's correct. And since you set content search engine to Windows Index so only files that is indexed are searched.

Looks like it's sufficient to solve your problem so I'm gonna close this issue. If you still have any question or it doesn't fix your issue, please feel free to reopen it.

**Comment by AaronB2019** [comment]
But my index search engine is on Everything. So, shouldn't searching test.txt shows me the file?

**Comment by VictoriousRaptor** [comment]
> But my index search engine is on Everything. So, shouldn't searching test.txt shows me the file?

You need to use the index search keyword to trigger index search i.e. Everything in your case. Please check that link for more details. If it's set to * and it's ENABLED but you still can't search files please check if your Everything is indexing D:\.

**Comment by AaronB2019** [comment]
Yes, as shown in the screenshot, the trigger is on *. When using everything to search, it works. It is indexing both my C: and D: and searching test.txt in there works. Just in the explorer plugin, it doesn't work.

**Comment by AaronB2019** [comment]
Ahh, ok it is disabled by default, I didn't notice, thank you 🙏

**Comment by VictoriousRaptor** [comment]
> Ahh, ok it is disabled by default, I didn't notice, thank you 🙏

If you don't care what kind of search is used, just set Search to * and enable it. It's default option.

**Comment by 3nigm4** [comment]
Hey there, I had the same problem as @AaronB2019 and just couldn't figure out why it wasn't working. I think the current design is really bad ui/ux design, because the greyed out is on grey and you would expect the "enable" setting in a column at right of the search keyword with a checkbox not in hidden in the dialog. Also the row does not indicate that it may open a dialog and last but not least the documentation does not show that there are further settings.

I mean well, I love Flow Launcher!
