### ISSUE TITLE
Move functionalities related to installing external plugins to PluginsManager

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#232]
Currently the ability to install external plugins is exposed via Flow.Launcher.Plugin.IPublicAPI.InstallPlugin(). This means any external plugins can install another plugin by calling this functionality and pass through the path to the zip file.

I think it will benefit the security of flow if we move this functionality and make it exclusive to only the default plugin that manages the installation of external plugins (in development [here](https://github.com/Flow-Launcher/Flow.Launcher/pull/231)). This will lock down flow and allow plugins to be only installed when it is approved via the PluginsManifest [repo](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest).

What do you people think?

@Flow-Launcher/team

**Comment by taooceros** [comment]
Sounds reasonable, but I believe currently plugin installed is done in Flow.Core.Plugin.PluginInstaller, which seems not be able to accessed by PluginsManager plugin. That's why the IPublicAPI expose an api for install plugin.

Is it possible to reference back or we will move all the funtionality from PluginInstaller to the new PluginManager plugin?

**Comment by jjw24** [comment]
i am planning to move the whole functionality to PluginsManager

**Comment by taooceros** [comment]
Sounds great.
