### ISSUE TITLE
Add exiting UI animation

### ISSUE THREAD

**Issue by bhiltune** [Flow-Launcher/Flow.Launcher#2634]
Currently Flow Launcher allows the user to change animation speed, which is great. Further customization could be added to improve the interface, however.

There is currently no animation when exiting Flow Launcher by clicking the ESC key, pressing a result, or clicking outside of the search bar. The app simply disappears abruptly. An added toggle to enable/disable this sort of exit animation would be great, and make navigation feel smoother and more modern, for people who enjoy this sort of thing. 

(For example, Windows 11 includes this sort of closing animation by default, with a slight fly-back/fade-out when you X out of an application. I believe MacOS does this as well, but I can't confirm.)

**Comment by onesounds** [comment]
I had built this but decided not to apply it. It creates a delay while the animation is running (the user has to wait for the animation to finish) and feels very awkward to use. 
The animation was intended to be an easy way to recognize the position of the window.  Since Flow is not a normal window, there are some issues with applying normal methods to it. I'm also considering removing some of the animations that currently exist. 
Personally, I prefer a nice-looking program, even if it's a bit inconvenient, so I think your opinion is worth considering. I'll consider it once the current priority issues (translucent windowing, etc.) are resolved.

Translated with DeepL.com (free version)

**Comment by ZGGSONG** [comment]
Don't add an exit animation, it can cause a lot of unexpected problems, I've recently been working on fixing the effects of exit animations in my project
