### ISSUE TITLE
FL is showing subfolders before the actual folder I'm searching for

### ISSUE THREAD

**Issue by christubuntu** [Flow-Launcher/Flow.Launcher#2878]
![FLOW SEARCH](https://github.com/user-attachments/assets/4dfa13a8-383b-493b-a296-343404ff4931)
![WINDOWS SEARCH](https://github.com/user-attachments/assets/05bd6750-7aba-4991-ba2d-de4e08e1cbef)

I have a folder named "DATA RECOVERY". Searching in Windows Search, the top result is the actual folder. In Flow Launcher (I use Windows search as indexer), top results are its subfolders. The actual folder is down at 7th position. How do I fix this? In

**Comment by rahulnoir** [comment]
You can just click set as topmost in this query in the context menu 🤷🏼‍♀️

**Comment by nanoraptor** [comment]
Learn everything's syntax from [here](https://www.voidtools.com/support/everything/searching/). You can use folder:DATA RECOVERY. If you want the same search results like the windows search as you've shown in your screenshot here, use windows index instead of everything index (You can change this in explorer plugin settings). You have much more flexibility over your search with everything. Once you learn the syntax you will appreciate how much better and logical it is. If you want regexes and the full syntax of everything to work with Flow Launcher, use [everything 1.5a](https://www.voidtools.com/everything-1.5a/). Troubleshoot the setup from [here](https://github.com/Flow-Launcher/Flow.Launcher/issues/1716).

**Comment by nanoraptor** [comment]
This issue can be closed now.
