### ISSUE TITLE
BUG: Pink theme is changed.

### ISSUE THREAD

**Issue by ubless607** [Flow-Launcher/Flow.Launcher#2906]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

The default theme 'pink' provided by the program is changed after I updated the software.

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

<img width="622" alt="1 18" src="https://github.com/user-attachments/assets/848a391a-a26b-43ac-a89a-0506304acb8b">
<img width="312" alt="1 19" src="https://github.com/user-attachments/assets/d4a06858-dc7d-4933-b6c9-fe0038bec2ec">

### Flow Launcher Version

1.19.0

### Windows Build Number

10.0.22631.4037

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by onesounds** [comment]
It's an intended design. We intended to delete the existing design because it has many overlapping elements with other themes, but we maintain it as an experimental theme. If you don't like the new design, we can provide you with a separate existing theme (I didn't think there would be people who like this theme). 😅

**Comment by ubless607** [comment]
@onesounds Can I get the old theme, please?

**Comment by onesounds** [comment]
https://file.io/lWIkiw4IT1ki
Try it.
