### ISSUE TITLE
Use TAB instead of SPACE to switch to arguments

### ISSUE THREAD

**Issue by dnngll** [Flow-Launcher/Flow.Launcher#2944]
Hello,

I'm used to pressing TAB in order to add arguments after a keyword, eg: "kill _**TAB**_ explorer" instead of "kill _**SPACE**_ explorer". Would it be possible do add this as an option in the settings?

Thanks : )

**Comment by nanoraptor** [comment]
But i think this would interfere with the default navigation hotkey which is the TAB key. But I do think this would enhance the utility of plugins as well as the separator changes to tab, it will easier for the plugin to identify when a word has been typed completely. because FL removes the spaces at the end of the query to make the plugins work ([Shortcuts plugin](https://github.com/mantasjasikenas/flow-launcher-shortcuts-plugin/issues/26#issuecomment-2351216448)). It has been somewhat discussed in #2605
