### ISSUE TITLE
BUG: Fix uninstall entry for Windows settings to allow 'uninstall' query

### ISSUE THREAD

**Issue by nanoraptor** [Flow-Launcher/Flow.Launcher#2979]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I am unable to get to the windows settings' uninstall menu. when I type s uninstall and enter, It just opens the settings app. If you look closely you will find that `s uninstall` does not even redirect to the path itself. It shows settings>mixed reality. 

### To Reproduce

1. type `s uninstall`
2. select the one with the windows settings icon

### Screenshots

![image](https://github.com/user-attachments/assets/82ab7f33-d7ee-4992-bd9d-e235be30f467)
![image](https://github.com/user-attachments/assets/0df073b1-bc6d-4d3a-b2a2-8174aaeaf078)

### Flow Launcher Version

1.19.1

### Windows Build Number

Microsoft Windows [Version 10.0.19045.4894]

**Comment by jjw24** [comment]
The uninstall settings page in windows 11 is now called 'Apps' or 'Apps Features' right?

**Comment by nanoraptor** [comment]
> The uninstall settings page in windows 11 is now called 'Apps' or 'Apps Features' right?

Well, in windows 10 it is called Apps Features. I don't know about windows 11. Although the apps can be uninstalled from there, the `s uninstall` should send me to the 'App Features' page and not the 'Mixed reality' one. That's my point here.

**Comment by weiluntong** [comment]
I do agree, I've typed `s uninstall` multiple times because from the normal start menu, I'm used to being able to type `uninstall`, in which it will take me to App Features (hilariously, typing `App Features` or `Apps` will not find the settings in the normal start, whereas flow will correctly find it with `s App Features` or `s Apps`). It doesn't help that in the normal start menu, if you type `uninstall`, the suggested result that will take you to the page you need to uninstall apps is titled as "Add or remove programs". So admittedly, I didn't know how to find that settings page (without manually opening Settings and click navigating to it) until I cam here and say "Apps" or "Apps Features".

Though I see that typing `s uninstall` *does* suggest the control panel version, which I'd very much like to keep as well, not sure if they fixed this, but I know early Windows Settings days, there were somethings you couldn't find in the Control Panel Uninstall window, and some things you couldn't find in the Windows Settings days.

I would still like to see the ability to reach "Apps"/"Apps Features" by typing `s uninstall` though.

**Comment by jjw24** [comment]
Yes I see the inconvenience, the plugin searches the item title and description to match your query, it's just the whole uninstall entry is inconveniently not containing the 'uninstall' word. I don't want to hardcode this word in the code, maybe there is something in the Settings plugin we can edit to add the word into the description.

**Comment by weiluntong** [comment]
actually, I 100% get you. hardcoded exceptions are a slippery slope. Oh! Speaking of word shortcuts. Out of scope of this issue, but is there partial matching for "Custom Query Shortcuts"? For example, I have "reboot" translating to "restart", and I also have "vscode" translate to "code" (personal tinfoil hat reasons against Microsoft). It'd be nice to partially match the queries to save some keystrokes.

**Comment by jjw24** [comment]
Yeah I forgot to mention you can use custom query to translate `s uninstall` to `s apps`.

Not 100% sure what you mean by partial matching,
