### ISSUE TITLE
Add Hebrew

### ISSUE THREAD

**Issue by Y-PLONI** [Flow-Launcher/Flow.Launcher#3111]
I would love for you to add Hebrew!
I tried to request it in crowdin and the system wouldn't let me.
I'd be happy if you would, and I'll try to translate.

**Comment by Y-PLONI** [comment]
???

**Comment by taooceros** [comment]
Sorry for the late reply. I will handle this today or tomorrow. If not please ping me.

**Comment by taooceros** [comment]
@Y-PLONI I have added Hebrew in Crowdin, and #3129 will add it in flow. If you would like, you could go to crowdin and translate Flow in Hebrew! https://crowdin.com/project/flow-launcher/

**Comment by H5820121** [comment]
@Y-PLONI 
Thanks for the Hebrew translation. If you could also work with the developers here so that when the language is Hebrew (or Arabic) then the display of the search window and results will be converted to RTL (and like in Windows Explorer and in Everything when you select Hebrew), that would be appreciated!

**Comment by Y-PLONI** [comment]
@H5820121 
You need to request this from: @taooceros

**Comment by H5820121** [comment]
@taooceros 
After @Y-PLONI  made an excellent translation into Hebrew, could you please make so that when the language is Hebrew (or Arabic) then the search window display and results will become RTL (like in Windows Explorer and Everything when you select Hebrew)?
