### ISSUE TITLE
Metasearch Functionality in Web Searches plugin.

### ISSUE THREAD

**Issue by Metroid-Prime** [Flow-Launcher/Flow.Launcher#438]
Entering this request per request made in Discord server. 
**** Please note - someone discord revealed there is a workaround for this already by entering multiple URLs with a space in between. Please don't 'fix' this until a proper design is implemented as it works pretty well so far. Thank you!****  

 The request is to allow user to enter multiple URLs in the Web Search plugin.   
![image](https://user-images.githubusercontent.com/1836362/118756104-0d34e780-b81f-11eb-94a4-c999663a72e7.png)

This is one of those features you never you needed until you set it up and use it. Why is this useful?  

The user can create "Deals <search string>" and it can search multiple sites like Slickdeals, Amazon, Pricewatcher, Google search w/ sale deal text, etc.   It allows the user to have a consistent way to easily search multiple places for things EXTREMELY quickly without having to type in each one.

**Comment by DRYN07** [comment]
Have you found any solution for this by any chance? I only use the abandoned Keypirinha app instead of any other launcher because it can handle multiple URLs simultaneously. As you said, you must use this feature once and then can't leave it. I made 2000 rows of my own queries over the years and I think it is essential nowadays to be very productive.

- you can search on more sites when you want to buy something
- open every page for a project you are working on
- etc

This is the only feature I miss from FlowLauncher since the beginning and after a while, I always check that maybe someone made a plugin for it. But as I see there is no solution yet :(

**Comment by jjw24** [comment]
>someone discord revealed there is a workaround for this already by entering multiple URLs with a space in between

Did you try this option as a workaround? Does the space in between work?

**Comment by jjw24** [comment]
Dup of #2097, tracking the issue over there.

**Comment by Vasdranna** [comment]
> > someone discord revealed there is a workaround for this already by entering multiple URLs with a space in between
> 
> Did you try this option as a workaround? Does the space in between work?

I was looking for this feature as well, tried that workaround but it doesn't work.

**Comment by jjw24** [comment]
Try the Shortcuts plugin, it solves issue.
