### ISSUE TITLE
Add "About" menu in the right-click sys tray

### ISSUE THREAD

**Issue by Metroid-Prime** [Flow-Launcher/Flow.Launcher#441]
![image](https://user-images.githubusercontent.com/1836362/118769328-ea153280-b834-11eb-946a-a6f142485011.png)

What do you guys think of adding an "About" entry in the Systray right click menu for Flow Control?  It should bring up this window for easy access to the version number. I've seen most apps do this. 

![image](https://user-images.githubusercontent.com/1836362/118769423-02854d00-b835-11eb-9129-49773c124813.png)

**Comment by onesounds** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/pull/763

It was considered in the above work, but the about menu is excluded because it is not frequently used.  the importance of putting it in this position is low.  When inserting, there is a problem of confusing other menu selection locations. There are ways to put it in the middle, but recently apps are removing 'about 'from tray menu. If the number of menus required increases in the future, we will consider inserting them.
