### ISSUE TITLE
Web Searches Not Working When Copied from Another Computer's Portable Install

### ISSUE THREAD

**Issue by mochigithub** [Flow-Launcher/Flow.Launcher#442]
**To Reproduce**
1. Tune a portable copy of FlowLauncher's web search plugin with custom keywords 
2. RAR or ZIP the file
3. Take install to another computer
4. Try to search with the same keyword.... e.g. "rm"  in this case.
5. Observe that the search keyword doesn't work
6. User has to go into websearch plugin, type a . Or some other letter in the action keyword space, confirm, then go back in and remove the . And confirm again.   The rm action keyword is working now. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1836362/118774042-4595ef00-b83a-11eb-8894-53a332c1683d.png)
![118773958-2c8d3e00-b83a-11eb-9210-c5a1262fe940](https://user-images.githubusercontent.com/1836362/118774579-d8368e00-b83a-11eb-88b6-538c00d929c9.png)

**Your System**
```

Flow Launcher version: 1.7.2
```
**Flow Launcher Error Log -- PLEASE START AT LINE 54 when I searched with "rm".   You can search for letters "Rm" to find the first hit in the log**

**Comment by taooceros** [comment]
Could you share the log? You can find the log by search with "Open Log Location"

**Comment by jjw24** [comment]
> Could you share the log? You can find the log by search with "Open Log Location"

Hey 'Open Log Location' feature has not been released yet, please see Flow's readme for the log location for now.

**Comment by jjw24** [comment]
Hmm this is indeed a strange bug, I have never come across this before and I have moved the same portable flow across a couple of computers.

**Comment by mochigithub** [comment]
This is incredibly strange. Even when I fix the search entry by putting a . or something in the keyword and then re-saving, on re-launch the websearch goes back to not working.

I'll have to hunt down logs or maybe even just zip the whole package together and send.  What do you think?

**Comment by taooceros** [comment]
Could you share the log? Without the log, it will be almost impossible to understand where gets wrong.

**Comment by taooceros** [comment]
C:\Users\1\AppData\Roaming\FlowLauncher\Settings\Settings.json

![image](https://user-images.githubusercontent.com/45326534/119210956-f5d95100-bae1-11eb-8753-904d2884ca03.png)

Find this part in the setting and modify the actionkeyword after closing Flow (to avoid saving) to the actionkeyword listed in the other computer to allow flow to reassign actionkeyword. This is because the actionkeyword settings and the plugin system are separated, so the Websearch plugin won't try to load actionkeyword from its setting.

**Comment by jjw24** [comment]
Closing this now, pretty sure it is fixed with https://github.com/Flow-Launcher/Flow.Launcher/pull/455. @mochigithub you can try the 1.8.0 in the pipeline [here](https://ci.appveyor.com/api/buildjobs/m41mx9xt2nwseq2f/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe), note it doesn't work with Everything yet if you are using it.
