### ISSUE TITLE
DotNetCore for plugins

### ISSUE THREAD

**Issue by NickSeagull** [Flow-Launcher/Flow.Launcher#65]
I was wondering if it is possible to develop plugins using DotNetCore instead of Net Framework, and if so, what would be the steps? I'd like to document this aswell.

**Comment by jjw24** [comment]
> I was wondering if it is possible to develop plugins using DotNetCore instead of Net Framework, and if so, what would be the steps? I'd like to document this aswell.

Hey how's it going. Not exactly sure what you mean but flow is .net core so core plugins work with it.

 .net framework plugins are the ones we will need to find a way to load them. I will work on loading .net framework plugins next if nobody else has taken it on.

To start you need to have the core sdk installed from vs 2019 or download manually. You can then create a WPF for .Net Core project. Once done you can install our Plugins project via Nuget, it's in beta but only because we have not officially release flow yet. Search Flow.Launchet.Plugins

I think @JohnTheGr8 is working on something like a standalone plugin template generator?

**Comment by NickSeagull** [comment]
Awesome, it's just I don't have much experience with packaging with either .net core or .net framework. I had created a plugin for Wox by following a tutorial using .net framework, and my plan was to port it to .net core + F#. Will try it and write a guide :)

Thanks!

**Comment by JohnTheGr8** [comment]
@NickSeagull you can copy the [HelloWorldFSharp](https://github.com/Flow-Launcher/Flow.Launcher/blob/master/Plugins/HelloWorldFSharp/) project files and build on top of that. 

If you need any help, hit me up!
