### ISSUE TITLE
About project itself suggestion: add `CHANGELOG.md` file

### ISSUE THREAD

**Issue by Zeroto521** [Flow-Launcher/Flow.Launcher#658]
There are already have release notes on the release page.
Why add a changelog (or history) file?

![image](https://user-images.githubusercontent.com/25895405/129823520-5f330f7e-e95e-4147-b7fd-83ae9714b209.png)
![image](https://user-images.githubusercontent.com/25895405/129823593-b4ea15d6-67e6-43db-a822-110af939f2ef.png)

Obviously, this is the result we could finally see.
But the path is hard to collect information.

Base on thinking, it should add a file to record change before a PR is merged.
And another benefit, all things could be traced in one file.

Use #623 to make an example.

```markdown
# ChangeLog

## Version 1.9.0 (2021-??-??)

### New Features

- Add Add Glyph Icon Support (#623)

### Fixed Bugs

...

```

**Comment by JohnTheGr8** [comment]
Use [the Releases page](https://github.com/Flow-Launcher/Flow.Launcher/releases), instead of the tags page, and you can view more releases and their release notes in one place...

That said, I do agree that we should link the issues/PRs of each change.

**Comment by jjw24** [comment]
Don't think changelog file is necessary, it's just extra maintenance when you can get the same result by going to the releases page or go to the pr section and filter by releases tag and see all the release pr and details of the change. You can also now filter by 'milestones' and see what prs each of the release contains. 

> I do agree that we should link the issues/PRs of each change.

I am ok to implement this, i didnt do it because thought the average user would not need to look at prs and if you are a dev you can always go to the release prs to get the same info plus the associated prs.

**Comment by jjw24** [comment]
I also agree GitHub Releases page is sufficient for end users, and release PRs have been containing pr links for a while now, so will close as won't implement. 

Feel free to re-open if further discussion is required.
