### ISSUE TITLE
Respect Windows Environment Path Variables

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#71]
Path Variables in Windows Explorer are sensitive to where certain directories are located. This is super helpful if you want to use the same config over multiple machines. 
For example, you could install OneDrive to be on `D:\OneDrive` or you just leave it to the default which is usually `C:\Users\{username}\OneDrive` (or `%UserProfile%\OneDrive`). Using Environment Path Variable `%OneDrive%` will always correctly resolve to where you installed OneDrive. As an example, I’m sharing my Windows Terminal `settings.json` for multiple machines using Environment Path Variables: `"backgroundImage": "%OneDrive%/.config/.assets/cmd.png"` works regardless where OneDrive is installed on multiple machines.

Similar to `%LocalAppData%` will respect the current user, in the manner: `C:\Users\{username}\AppData\Local`

Flow does not support path variables. It would be cool if we could just enter them the corresponding path will be auto-completed.

Helpful Links:
- https://superuser.com/questions/217504/is-there-a-list-of-windows-special-directories-shortcuts-like-temp
- https://ss64.com/nt/syntax-variables.html

**Comment by jjw24** [comment]
Hey @Kalaschnik how's it going.

Flow already supports environment variables and path search. 

I introduced a bug when i did the Explorer plugin and it was not activated at all. This is fixed in PR #72

Until this fix goes out, you can test out the fix here https://ci.appveyor.com/api/buildjobs/5f7n083fdyv23o4c/artifacts/Output%2FPackages%2FFlow-Launcher-v0.9.0.zip

**Comment by Kalaschnik** [comment]
Oh, I was not aware of this. Thanks!
