### ISSUE TITLE
Bookmarks plugin not working for new Edge Browser

### ISSUE THREAD

**Issue by Kalaschnik** [Flow-Launcher/Flow.Launcher#75]
rel:
https://github.com/Wox-launcher/Wox/issues/3077

**Comment by JohnTheGr8** [comment]
ready for the upcoming release

**Comment by tomgwilliams** [comment]
> ready for the upcoming release

I'm running Edge version 85.0.564.63 [(64-bit) as my default browser, but looks like it's only picking up the bookmarks from Chrome or Firefox (which I also have installed).

Is the Boookmarks plugin looking to the bookmarks of the browser specified by the 'Browser Path' in the UI? Or the browser set as the computer's default?

**Comment by jjw24** [comment]
> > ready for the upcoming release
> 
> I'm running Edge version 85.0.564.63 [(64-bit) as my default browser, but looks like it's only picking up the bookmarks from Chrome or Firefox (which I also have installed).

That's strange it should be picking up automatically along with bookmarks from firefox and chrome. 

Can you do a reload plugin data and see if they come up. Let me know, if still nothing I will boot up a VM to check as I don't use edge atm.



> Is the Boookmarks plugin looking to the bookmarks of the browser specified by the 'Browser Path' in the UI? Or the browser set as the computer's default? OR, to all the supported browser bookmark directories, building them all into a single bookmarks library in the plugin.

Yep it's looking into the default bookmark store directory for the three supported browsers and building them into a single bookmarks library in the plugin. Browser path is for specifying whether you want to use Firefox instead of the default ie or chrome.

Also it sounds like you have your edge installed somewhere else rather than the default location?
