### ISSUE TITLE
Disable installed plugins from plugin store and add "installed" label

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#896]
Currently, even the installed plugins can be installed again but you get a notification that the plugin is already installed.

Maybe the buttons for the installed plugins can be disabled and an "installed" label can be added to the button.
 
![Flow](https://user-images.githubusercontent.com/47380919/145695945-63586a60-0cd5-4275-8c61-f63be0de9c8b.jpg)

**Comment by rp1231** [comment]
Maybe an uninstall button can be added in place of the "Installed" label ?

**Comment by onesounds** [comment]
yeah. good idea. There was a plan. (Installed label + category label. Uninstall will be displayed instead of the install button as you said, and will also be added to the plugin description item.) but it was not possible to a lot of resources to the work. The importance is not high, so it is scheduled to work later. Search menus and paging will be worked on first and sequentially.
