### ISSUE TITLE
Getting "Update Failed" notification with 1.9 

### ISSUE THREAD

**Issue by katchy3132** [Flow-Launcher/Flow.Launcher#905]
**Describe the bug/issue**
Periodically getting the error " Update Failed: Check your connection and try updating proxy settings to  github-cloud.s3.amazonaws.com " 

**To Reproduce**
around one a day this Windows notification shows up 
**Screenshots**
![image](https://user-images.githubusercontent.com/3707138/146242466-8bc2f1d9-637c-486a-82d2-063d95024b8e.png)

**Your System**
```
Windows build number: [Version 10.0.19044.1387] 
Flow Launcher version: 1.9 
```
**Flow Launcher Error Log**

[2021-12-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7721829/2021-12-15.txt)

**Comment by taooceros** [comment]
Are you in China?

**Comment by katchy3132** [comment]
nope. I can ping /https  api.github.com without problems. 

> Are you in China? Github api access can be unstable in china.

**Comment by onesounds** [comment]
It is presumed that this occurs as a problem of network connection failure when attempting automatic update. Since automatic update is not the action intended by the user when the network is not connected, I think it is right that there is no feedback even if the connection fails. If the user has attempted to update, it is right to show the notification then.

It is difficult for us to identify network problems. If you think this part is also something we need to fix, please let me know again. I think your problem is where unwanted notifications come up, so we're going to focus on this part.

**Comment by katchy3132** [comment]
That sounds right. It must be some quirk when it automatically checks. 
When I click "Check for Update" It says "you already have the latest version" so that seemingly works correctly.
