### ISSUE TITLE
[Feature Request] - ability to bulk update plugins

### ISSUE THREAD

**Issue by deefrawley** [Flow-Launcher/Flow.Launcher#980]
It would be good to have the ability to tell Flow to update all outdated plugins with one command.
Perhaps a new command like `pm update all`

**Comment by jjw24** [comment]
maybe just something like `pm update` and the top result is update all result if more than one plugin needs updated.

**Comment by deefrawley** [comment]
Yeah that would work. Save introducing a new argument.

**Comment by flooxo** [comment]
I guess in order to solve this issue/implement the new option this method has to be updated. What's the best way show the option `all` only after `pm update` has been written?
I'd like to implement this option because it would be very handy :)
https://github.com/Flow-Launcher/Flow.Launcher/blob/6ed7453c7703ece3075bcfb26ef8040a8cec7194/Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs#L78-L88

**Comment by flooxo** [comment]
> `pm update` and the top result is update all

That would be a possibility or what would also be practicable is a kind of flag that you call it with `pm update -a` or `pm update --all`

**Comment by jjw24** [comment]
I think to keep it simple for users, just display a top result to update all plugins when more than one plugin has an update :)
